import {
  CANVAS_APP_COMMAND_PALETTE_FEATURE_PACK_MANIFEST,
} from './command-palette'
import {
  CANVAS_APP_COMPONENT_AUTHORING_FEATURE_PACK_MANIFEST,
} from './component-authoring'
import {
  CANVAS_APP_CURSOR_CHAT_FEATURE_PACK_MANIFEST,
} from './cursor-chat'
import {
  CANVAS_APP_DRAWING_TOOLS_FEATURE_PACK_MANIFEST,
} from './drawing-tools'
import {
  CANVAS_APP_FACILITATION_FEATURE_PACK_MANIFEST,
} from './facilitation'
import {
  CANVAS_APP_FIND_REPLACE_FEATURE_PACK_MANIFEST,
} from './find-replace'
import {
  CANVAS_APP_IMAGE_IO_FEATURE_PACK_MANIFEST,
} from './image-io'
import {
  CANVAS_APP_MINIMAP_FEATURE_PACK_MANIFEST,
} from './minimap'
import {
  CANVAS_APP_SELECTION_TOOLBAR_FEATURE_PACK_MANIFEST,
} from './selection-toolbar'
import {
  CANVAS_APP_SHORTCUT_HELP_FEATURE_PACK_MANIFEST,
} from './shortcut-help'
import {
  CANVAS_APP_STAMP_AUTHORING_FEATURE_PACK_MANIFEST,
} from './stamp-authoring'
import {
  CANVAS_APP_STATUS_BAR_FEATURE_PACK_MANIFEST,
} from './status-bar'
import {
  CANVAS_APP_TOOLBAR_FEATURE_PACK_MANIFEST,
} from './toolbar'
import {
  CANVAS_APP_ZOOM_CONTROLS_FEATURE_PACK_MANIFEST,
} from './zoom-controls'
import {
  getCanvasAppManifestViewFeaturePacks,
  type CanvasAppFeaturePackManifest,
} from './CanvasAppFeaturePackManifests'
import {
  createCanvasAppFeaturePackViewRenderers,
  type CanvasAppViewFeaturePack,
} from './CanvasAppFeaturePackViews'

export {
  CANVAS_APP_COMMAND_PALETTE_FEATURE_PACK_MANIFEST,
  CANVAS_APP_COMMAND_PALETTE_VIEW_FEATURE_PACK,
} from './command-palette'
export {
  CANVAS_APP_COMPONENT_AUTHORING_FEATURE_PACK_MANIFEST,
  CANVAS_APP_COMPONENT_AUTHORING_VIEW_FEATURE_PACK,
} from './component-authoring'
export {
  CANVAS_APP_CURSOR_CHAT_FEATURE_PACK_MANIFEST,
  CANVAS_APP_CURSOR_CHAT_VIEW_FEATURE_PACK,
} from './cursor-chat'
export {
  CANVAS_APP_DRAWING_TOOLS_FEATURE_PACK_MANIFEST,
  CANVAS_APP_DRAWING_TOOLS_VIEW_FEATURE_PACK,
} from './drawing-tools'
export {
  CANVAS_APP_FACILITATION_FEATURE_PACK_MANIFEST,
  CANVAS_APP_FACILITATION_VIEW_FEATURE_PACK,
} from './facilitation'
export {
  CANVAS_APP_FIND_REPLACE_FEATURE_PACK_MANIFEST,
  CANVAS_APP_FIND_REPLACE_VIEW_FEATURE_PACK,
} from './find-replace'
export {
  CANVAS_APP_IMAGE_IO_FEATURE_PACK_MANIFEST,
  CANVAS_APP_IMAGE_IO_VIEW_FEATURE_PACK,
} from './image-io'
export {
  CANVAS_APP_MINIMAP_FEATURE_PACK_MANIFEST,
  CANVAS_APP_MINIMAP_VIEW_FEATURE_PACK,
} from './minimap'
export {
  CANVAS_APP_SELECTION_TOOLBAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_SELECTION_TOOLBAR_VIEW_FEATURE_PACK,
} from './selection-toolbar'
export {
  CANVAS_APP_SHORTCUT_HELP_FEATURE_PACK_MANIFEST,
  CANVAS_APP_SHORTCUT_HELP_VIEW_FEATURE_PACK,
} from './shortcut-help'
export {
  CANVAS_APP_STAMP_AUTHORING_FEATURE_PACK_MANIFEST,
  CANVAS_APP_STAMP_AUTHORING_VIEW_FEATURE_PACK,
} from './stamp-authoring'
export {
  CANVAS_APP_STATUS_BAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_STATUS_BAR_VIEW_FEATURE_PACK,
} from './status-bar'
export {
  CANVAS_APP_TOOLBAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_TOOLBAR_VIEW_FEATURE_PACK,
} from './toolbar'
export {
  CANVAS_APP_ZOOM_CONTROLS_FEATURE_PACK_MANIFEST,
  CANVAS_APP_ZOOM_CONTROLS_VIEW_FEATURE_PACK,
} from './zoom-controls'

export const DEFAULT_CANVAS_APP_VIEW_FEATURE_PACK_MANIFESTS = Object.freeze([
  CANVAS_APP_COMMAND_PALETTE_FEATURE_PACK_MANIFEST,
  CANVAS_APP_COMPONENT_AUTHORING_FEATURE_PACK_MANIFEST,
  CANVAS_APP_CURSOR_CHAT_FEATURE_PACK_MANIFEST,
  CANVAS_APP_DRAWING_TOOLS_FEATURE_PACK_MANIFEST,
  CANVAS_APP_FACILITATION_FEATURE_PACK_MANIFEST,
  CANVAS_APP_FIND_REPLACE_FEATURE_PACK_MANIFEST,
  CANVAS_APP_IMAGE_IO_FEATURE_PACK_MANIFEST,
  CANVAS_APP_MINIMAP_FEATURE_PACK_MANIFEST,
  CANVAS_APP_SELECTION_TOOLBAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_SHORTCUT_HELP_FEATURE_PACK_MANIFEST,
  CANVAS_APP_STAMP_AUTHORING_FEATURE_PACK_MANIFEST,
  CANVAS_APP_STATUS_BAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_TOOLBAR_FEATURE_PACK_MANIFEST,
  CANVAS_APP_ZOOM_CONTROLS_FEATURE_PACK_MANIFEST,
]) satisfies readonly CanvasAppFeaturePackManifest[]

export const DEFAULT_CANVAS_APP_VIEW_FEATURE_PACKS =
  getCanvasAppManifestViewFeaturePacks(
    DEFAULT_CANVAS_APP_VIEW_FEATURE_PACK_MANIFESTS,
  ) satisfies readonly CanvasAppViewFeaturePack[]

export const DEFAULT_CANVAS_APP_FEATURE_PACK_VIEW_RENDERERS =
  createCanvasAppFeaturePackViewRenderers(DEFAULT_CANVAS_APP_VIEW_FEATURE_PACKS)
