import {
  CANVAS_APP_COMPONENT_AUTHORING_FEATURE_PACK_MANIFEST,
} from './component-authoring'
import {
  CANVAS_APP_COMPONENT_INSPECTOR_FEATURE_PACK_MANIFEST,
} from './component-inspector'
import {
  CANVAS_APP_COMPONENT_SYNC_FEATURE_PACK_MANIFEST,
} from './component-sync'
import {
  CANVAS_APP_COMPONENT_LIBRARY_FEATURE_PACK_MANIFEST,
} from './component-library'
import {
  CANVAS_APP_COMPONENT_SOURCE_OUTLINE_FEATURE_PACK_MANIFEST,
} from './component-source-outline'
import {
  CANVAS_APP_COMMAND_PALETTE_FEATURE_PACK_MANIFEST,
} from './command-palette'
import {
  CANVAS_APP_BOARD_IO_FEATURE_PACK_MANIFEST,
} from './board-io'
import {
  CANVAS_APP_DRAWING_TOOLS_FEATURE_PACK_MANIFEST,
} from './drawing-tools'
import {
  CANVAS_APP_IMAGE_IO_FEATURE_PACK_MANIFEST,
} from './image-io'
import {
  CANVAS_APP_MEDIA_IMPORT_FEATURE_PACK_MANIFEST,
} from './media-import'
import {
  CANVAS_APP_SHAPE_AUTHORING_FEATURE_PACK_MANIFEST,
} from './shape-authoring'
import {
  CANVAS_APP_STAMP_AUTHORING_FEATURE_PACK_MANIFEST,
} from './stamp-authoring'
import {
  CANVAS_APP_TABLE_IMPORT_FEATURE_PACK_MANIFEST,
} from './table-import'
import {
  CANVAS_APP_TEXT_PASTE_IMPORT_FEATURE_PACK_MANIFEST,
} from './text-paste-import'
import {
  CANVAS_STORY_PREVIEW_ITEMS_FEATURE_PACK_ID,
} from './story-preview'
import {
  CANVAS_APP_STORY_IMPORT_FEATURE_PACK_MANIFEST,
} from './story-import'
import {
  CANVAS_APP_TOOLBAR_FEATURE_PACK_MANIFEST,
} from './toolbar'
import {
  createCanvasAppFeaturePackSuiteManifest,
  type CanvasAppFeaturePackSuiteManifest,
} from './CanvasAppFeaturePackSuites'

export const CANVAS_AUTHORING_BASICS_SUITE_ID = 'authoring-basics'
export const CANVAS_COMPONENT_SYSTEM_SUITE_ID = 'component-system'
export const CANVAS_IMPORT_EXPORT_SUITE_ID = 'import-export'
export const CANVAS_STORY_CANVAS_SUITE_ID = 'story-canvas'

export const CANVAS_AUTHORING_BASICS_FEATURE_PACK_SUITE_MANIFEST =
  createCanvasAppFeaturePackSuiteManifest({
    featurePackIds: [
      CANVAS_APP_SHAPE_AUTHORING_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_DRAWING_TOOLS_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_STAMP_AUTHORING_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_TOOLBAR_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_COMMAND_PALETTE_FEATURE_PACK_MANIFEST.id,
    ],
    id: CANVAS_AUTHORING_BASICS_SUITE_ID,
    label: 'Authoring basics',
  })

export const CANVAS_COMPONENT_SYSTEM_FEATURE_PACK_SUITE_MANIFEST =
  createCanvasAppFeaturePackSuiteManifest({
    featurePackIds: [
      CANVAS_APP_COMPONENT_LIBRARY_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_COMPONENT_SOURCE_OUTLINE_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_COMPONENT_SYNC_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_COMPONENT_INSPECTOR_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_COMPONENT_AUTHORING_FEATURE_PACK_MANIFEST.id,
    ],
    id: CANVAS_COMPONENT_SYSTEM_SUITE_ID,
    label: 'Component system',
  })

export const CANVAS_IMPORT_EXPORT_FEATURE_PACK_SUITE_MANIFEST =
  createCanvasAppFeaturePackSuiteManifest({
    featurePackIds: [
      CANVAS_APP_IMAGE_IO_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_MEDIA_IMPORT_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_TABLE_IMPORT_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_TEXT_PASTE_IMPORT_FEATURE_PACK_MANIFEST.id,
      CANVAS_APP_BOARD_IO_FEATURE_PACK_MANIFEST.id,
    ],
    id: CANVAS_IMPORT_EXPORT_SUITE_ID,
    label: 'Import/export',
  })

export const CANVAS_STORY_CANVAS_FEATURE_PACK_SUITE_MANIFEST =
  createCanvasAppFeaturePackSuiteManifest({
    featurePackIds: [
      CANVAS_STORY_PREVIEW_ITEMS_FEATURE_PACK_ID,
      CANVAS_APP_STORY_IMPORT_FEATURE_PACK_MANIFEST.id,
    ],
    id: CANVAS_STORY_CANVAS_SUITE_ID,
    label: 'Story Canvas',
  })

export const DEFAULT_CANVAS_APP_FEATURE_PACK_SUITE_MANIFESTS = Object.freeze([
  CANVAS_AUTHORING_BASICS_FEATURE_PACK_SUITE_MANIFEST,
  CANVAS_COMPONENT_SYSTEM_FEATURE_PACK_SUITE_MANIFEST,
  CANVAS_IMPORT_EXPORT_FEATURE_PACK_SUITE_MANIFEST,
  CANVAS_STORY_CANVAS_FEATURE_PACK_SUITE_MANIFEST,
]) satisfies readonly CanvasAppFeaturePackSuiteManifest[]
