import { useCanvasKeyboardShortcuts } from '../affordances/interaction/keyboard/useCanvasKeyboardShortcuts'
import { editCanvasAppSelectionText } from './CanvasAppSelectionModel'
import type { CanvasAppKeyboardModelInput } from './CanvasAppKeyboardConsumerContracts'

export function useCanvasAppKeyboardModel({
  command,
  component,
  config,
  cursorChat,
  customCommands,
  customCreationTools,
  interaction,
  openCommandPalette,
  openFindReplace,
  openShortcutHelp,
  runCustomCommand,
  viewport,
  workspace,
}: CanvasAppKeyboardModelInput) {
  useCanvasKeyboardShortcuts({
    commitSelection: workspace.command.commitSelection,
    config,
    closeCursorChat: cursorChat.closeCursorChat,
    copySelection: command.copySelection,
    customCommands,
    customCreationTools,
    cutSelection: command.cutSelection,
    deleteSelection: command.deleteSelection,
    duplicateSelection: command.duplicateSelection,
    editSelection: () =>
      editCanvasAppSelectionText({
        canEditText: workspace.canEditText,
        itemReadModel: workspace.itemReadModel,
        selection: workspace.selection,
        setEditing: interaction.setEditing,
      }),
    fitToItems: viewport.fitToItems,
    groupSelection: command.groupSelection,
    interactionRef: interaction.interactionRef,
    lockSelection: command.lockSelection,
    moveSelection: command.moveSelection,
    openCommandPalette,
    openCursorChat: cursorChat.openCursorChat,
    openFindReplace,
    openShortcutHelp,
    pasteSelection: command.pasteSelection,
    quickCreateSticky: component.quickCreateSticky,
    redoHistory: command.redoHistory,
    reorderSelection: command.reorderSelection,
    resetViewport: viewport.resetViewport,
    selectAll: command.selectAll,
    selection: workspace.selection,
    setDraftArrow: interaction.setDraftArrow,
    setDraftRect: interaction.setDraftRect,
    setDraftStroke: interaction.setDraftStroke,
    setLaserTrail: interaction.setLaserTrail,
    setEditing: interaction.setEditing,
    setGesture: interaction.setGesture,
    setMarquee: interaction.setMarquee,
    setSpaceDown: interaction.setSpaceDown,
    runCustomCommand,
    setTool: interaction.setTool,
    undoHistory: command.undoHistory,
    ungroupSelection: command.ungroupSelection,
    unlockAll: command.unlockAll,
    zoom: viewport.zoom,
  })
}
