import type { CanvasStoryEvent } from './CanvasStoryEvents'

export const DEMO_REPO_STORY_EVENTS = [
  {
    v: 1,
    type: 'section',
    id: 'operating-state',
    lane: 'intake',
    title: 'Operating State',
    purpose: 'Top-level status for the generated workspace.',
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'operating-summary',
    sectionId: 'operating-state',
    title: 'Live state',
    summary: 'Review needs are visible before publish.',
    metrics: [
      { label: 'Run', value: 'Review', detail: '6 warnings' },
      { label: 'Trace', value: '78%', detail: 'risk claims' },
      { label: 'Gate', value: 'Open', detail: 'owner gap' },
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'mission-brief',
    lane: 'intake',
    title: 'Mission Brief',
    purpose: 'Enterprise onboarding workspace generated from one product brief.',
  },
  {
    v: 1,
    type: 'table',
    id: 'account-context',
    sectionId: 'mission-brief',
    title: 'Account profile',
    columns: ['Field', 'Signal'],
    rows: [
      ['Segment', 'Tier-1 bank'],
      ['Rollout', 'EMEA regulated'],
      ['Audience', '1.2k users'],
    ],
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'success-metrics',
    sectionId: 'mission-brief',
    title: 'Target outcomes',
    summary: 'Business targets extracted from the account brief.',
    metrics: [
      { label: 'Users', value: '1.2k', detail: 'target activation' },
      { label: 'Time', value: '-32%', detail: 'setup effort' },
      { label: 'Audit', value: '100%', detail: 'source trace' },
    ],
  },
  {
    v: 1,
    type: 'evidence',
    id: 'brief-inputs',
    sectionId: 'mission-brief',
    title: 'Brief inputs',
    rows: [
      { source: 'CRM notes', signal: 'expansion risk', state: 'verified' },
      { source: 'Support', signal: 'security blockers', state: 'verified' },
      { source: 'Sales call', signal: 'stakeholder map', state: 'new' },
    ],
  },
  {
    v: 1,
    type: 'note',
    id: 'brief-lock',
    sectionId: 'mission-brief',
    title: 'Locked scope',
    body: 'No claims without source trace.',
  },
  {
    v: 1,
    type: 'section',
    id: 'generation-run',
    lane: 'intake',
    title: 'Generation Run',
    purpose: 'Source signals become governed workspace objects.',
  },
  {
    v: 1,
    type: 'table',
    id: 'prompt-bundle',
    sectionId: 'generation-run',
    title: 'Prompt bundle',
    columns: ['Input', 'Use'],
    rows: [
      ['Brief', 'scope'],
      ['Brand', 'voice rules'],
      ['Examples', 'approved pattern'],
    ],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'schema-gate',
    sectionId: 'generation-run',
    title: 'Schema gate',
    items: ['Valid event', 'Stable id', 'Known owner'],
    checked: ['Valid event', 'Stable id'],
  },
  {
    v: 1,
    type: 'timeline',
    id: 'run-state',
    sectionId: 'generation-run',
    title: 'Run state',
    steps: ['Parse', 'Stream', 'Resolve', 'Commit'],
    completed: 3,
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'run-metrics',
    sectionId: 'generation-run',
    title: 'Run metrics',
    summary: 'Current run health and review exposure.',
    metrics: [
      { label: 'Events', value: '47', detail: 'streamed' },
      { label: 'Warnings', value: '6', detail: 'review needed' },
      { label: 'Latency', value: '18s', detail: 'end to end' },
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'generated-board',
    lane: 'intake',
    title: 'Workspace Plan',
    purpose: 'Account workspace ready for inspection, edit, and publish.',
  },
  {
    v: 1,
    type: 'table',
    id: 'journey-lanes',
    sectionId: 'generated-board',
    title: 'Journey lanes',
    columns: ['Lane', 'Owner'],
    rows: [
      ['Buyer', 'GTM'],
      ['Admin', 'IT'],
      ['End user', 'CS'],
    ],
  },
  {
    v: 1,
    type: 'queue',
    id: 'control-points',
    sectionId: 'generated-board',
    title: 'Control points',
    items: ['SLA owner', 'Legal gate', 'Security review'],
    done: ['SLA owner'],
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'artifact-mix',
    sectionId: 'generated-board',
    title: 'Artifact mix',
    summary: 'Workspace composition across regions, items, and relations.',
    metrics: [
      { label: 'Sections', value: '9', detail: 'workspace regions' },
      { label: 'Objects', value: '47', detail: 'generated items' },
      { label: 'Relations', value: '10', detail: 'routed edges' },
    ],
  },
  {
    v: 1,
    type: 'note',
    id: 'layout-policy',
    sectionId: 'generated-board',
    title: 'Density policy',
    body: 'Review workspace, not a presentation deck.',
  },
  {
    v: 1,
    type: 'section',
    id: 'evidence-map',
    lane: 'generation',
    title: 'Evidence Map',
    purpose: 'Generated claims stay linked to source evidence.',
  },
  {
    v: 1,
    type: 'table',
    id: 'source-traces',
    sectionId: 'evidence-map',
    title: 'Trace sources',
    columns: ['Source', 'Use'],
    rows: [
      ['CRM note', 'commercial claim'],
      ['Support ticket', 'blocker claim'],
      ['Call transcript', 'workflow claim'],
    ],
  },
  {
    v: 1,
    type: 'evidence',
    id: 'claim-evidence',
    sectionId: 'evidence-map',
    title: 'Claim evidence',
    rows: [
      { source: 'Ticket #8142', signal: 'Security blocker', state: 'linked' },
      { source: 'AE note', signal: 'Upsell timing', state: 'linked' },
      { source: 'Call clip', signal: 'Admin pain', state: 'linked' },
    ],
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'trace-coverage',
    sectionId: 'evidence-map',
    title: 'Trace coverage',
    summary: 'Coverage shows whether claims can survive review.',
    metrics: [
      { label: 'Revenue', value: '92%', detail: 'covered' },
      { label: 'Risk', value: '78%', detail: 'covered' },
      { label: 'Owners', value: '61%', detail: 'needs work' },
    ],
  },
  {
    v: 1,
    type: 'risk',
    id: 'evidence-gap-risk',
    sectionId: 'evidence-map',
    title: 'Owner gap',
    severity: 'Medium',
  },
  {
    v: 1,
    type: 'section',
    id: 'canvas-tools',
    lane: 'generation',
    title: 'Control Surface',
    purpose: 'Contextual controls stay close to the active workspace.',
  },
  {
    v: 1,
    type: 'table',
    id: 'primary-tools',
    sectionId: 'canvas-tools',
    title: 'Navigation',
    columns: ['Control', 'Mode'],
    rows: [
      ['Select', 'work object'],
      ['Pan', 'canvas'],
      ['Arrow', 'relation'],
    ],
  },
  {
    v: 1,
    type: 'queue',
    id: 'edit-tools',
    sectionId: 'canvas-tools',
    title: 'Edit actions',
    items: ['Duplicate', 'Group', 'Inspect', 'Undo'],
    done: ['Duplicate', 'Group'],
  },
  {
    v: 1,
    type: 'table',
    id: 'tool-policy',
    sectionId: 'canvas-tools',
    title: 'Control policy',
    columns: ['Control', 'Rule'],
    rows: [
      ['Palette', 'hidden until useful'],
      ['Inspector', 'selection-only'],
      ['Zoom', 'persistent'],
    ],
  },
  {
    v: 1,
    type: 'note',
    id: 'tool-rule',
    sectionId: 'canvas-tools',
    title: 'Visibility rule',
    body: 'Show controls only when they affect the selected work.',
  },
  {
    v: 1,
    type: 'section',
    id: 'review-queue',
    lane: 'review',
    title: 'Review Queue',
    purpose: 'Human review turns generated content into an approved plan.',
  },
  {
    v: 1,
    type: 'table',
    id: 'pm-review',
    sectionId: 'review-queue',
    title: 'PM review',
    columns: ['Check', 'State'],
    rows: [
      ['Priority', 'set'],
      ['Dependencies', 'open'],
      ['Timeline', 'draft'],
    ],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'design-review',
    sectionId: 'review-queue',
    title: 'Design review',
    items: ['Naming', 'Flow', 'Visual density'],
    checked: ['Naming'],
  },
  {
    v: 1,
    type: 'queue',
    id: 'review-status',
    sectionId: 'review-queue',
    title: 'Review status',
    items: ['Resolve duplicates', 'Check owners', 'Approve publish', 'Send to docs'],
    done: ['Resolve duplicates', 'Check owners'],
  },
  {
    v: 1,
    type: 'risk',
    id: 'unsupported-claim-risk',
    sectionId: 'review-queue',
    title: 'Unsupported claim',
    severity: 'High',
  },
  {
    v: 1,
    type: 'section',
    id: 'governance',
    lane: 'review',
    title: 'Governance',
    purpose: 'Enterprise review rules apply before publish.',
  },
  {
    v: 1,
    type: 'decision',
    id: 'publish-decision',
    sectionId: 'governance',
    title: 'Publish decision',
    option: 'Publish only after evidence and owner gates pass',
    status: 'proposed',
  },
  {
    v: 1,
    type: 'risk',
    id: 'compliance-risk',
    sectionId: 'governance',
    title: 'Compliance drift',
    severity: 'Medium',
  },
  {
    v: 1,
    type: 'timeline',
    id: 'approval-gates',
    sectionId: 'governance',
    title: 'Approval gates',
    steps: ['Evidence', 'Legal', 'Security', 'Audit'],
    completed: 1,
  },
  {
    v: 1,
    type: 'evidence',
    id: 'audit-log',
    sectionId: 'governance',
    title: 'Audit log',
    rows: [
      { source: 'Owner', signal: 'changed field', state: 'logged' },
      { source: 'Reviewer', signal: 'accepted claim', state: 'logged' },
      { source: 'Policy', signal: 'release gate', state: 'open' },
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'quality-bar',
    lane: 'review',
    title: 'Quality Gates',
    purpose: 'Automated checks block weak workspaces before review.',
  },
  {
    v: 1,
    type: 'checklist',
    id: 'density-check',
    sectionId: 'quality-bar',
    title: 'Density check',
    items: ['Readable at 60%', 'No overlaps', 'Balanced sections'],
    checked: ['No overlaps'],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'semantic-check',
    sectionId: 'quality-bar',
    title: 'Semantic check',
    items: ['Clear owner', 'Clear relation', 'Clear action'],
    checked: ['Clear relation'],
  },
  {
    v: 1,
    type: 'scorecard',
    id: 'qa-results',
    sectionId: 'quality-bar',
    title: 'Gate results',
    summary: 'Automated checks summarized for reviewer action.',
    metrics: [
      { label: 'Schema', value: 'Pass', detail: '0 invalid' },
      { label: 'Evidence', value: 'Review', detail: '4 claims' },
      { label: 'Layout', value: 'Pass', detail: '0 overlaps' },
    ],
  },
  {
    v: 1,
    type: 'risk',
    id: 'readability-risk',
    sectionId: 'quality-bar',
    title: 'Dense copy',
    severity: 'Low',
  },
  {
    v: 1,
    type: 'section',
    id: 'integrations',
    lane: 'delivery',
    title: 'Integrations',
    purpose: 'Approved workspace connects back to systems of record.',
  },
  {
    v: 1,
    type: 'table',
    id: 'crm-sync',
    sectionId: 'integrations',
    title: 'CRM sync',
    columns: ['Object', 'Mode'],
    rows: [
      ['Account', 'read/write'],
      ['Opportunity', 'read'],
      ['Contacts', 'read'],
    ],
  },
  {
    v: 1,
    type: 'table',
    id: 'doc-export',
    sectionId: 'integrations',
    title: 'Doc export',
    columns: ['Artifact', 'Target'],
    rows: [
      ['Brief', 'Docs'],
      ['Playbook', 'CS workspace'],
      ['Risk appendix', 'Audit pack'],
    ],
  },
  {
    v: 1,
    type: 'evidence',
    id: 'system-map',
    sectionId: 'integrations',
    title: 'System map',
    rows: [
      { source: 'CRM', signal: 'read/write account truth', state: 'RevOps' },
      { source: 'Docs', signal: 'write playbook package', state: 'CS Ops' },
      { source: 'BI', signal: 'read adoption metrics', state: 'Analytics' },
    ],
  },
  {
    v: 1,
    type: 'decision',
    id: 'integration-choice',
    sectionId: 'integrations',
    title: 'System choice',
    option: 'CRM remains the source of account truth',
    status: 'decided',
  },
  {
    v: 1,
    type: 'section',
    id: 'publish-ready',
    lane: 'delivery',
    title: 'Release Package',
    purpose: 'Approved workspace becomes the shared operating plan.',
  },
  {
    v: 1,
    type: 'table',
    id: 'release-package',
    sectionId: 'publish-ready',
    title: 'Release package',
    columns: ['Output', 'State'],
    rows: [
      ['Canvas', 'ready'],
      ['Brief', 'ready'],
      ['Tasks', 'assigned'],
      ['Changelog', 'open'],
    ],
  },
  {
    v: 1,
    type: 'queue',
    id: 'publish-checklist',
    sectionId: 'publish-ready',
    title: 'Publish checklist',
    items: ['Review closed', 'Owners assigned', 'Exports generated', 'Archive source'],
    done: ['Review closed', 'Owners assigned'],
  },
  {
    v: 1,
    type: 'decision',
    id: 'handoff-decision',
    sectionId: 'publish-ready',
    title: 'Handoff mode',
    option: 'Send to customer success workspace',
    status: 'decided',
  },
  {
    v: 1,
    type: 'note',
    id: 'publish-note',
    sectionId: 'publish-ready',
    title: 'Release signal',
    body: 'Approved artifacts are ready for customer success handoff.',
  },
  {
    v: 1,
    type: 'edge',
    id: 'brief-feeds-run',
    from: 'mission-brief',
    to: 'operating-state',
    relation: 'feeds',
    label: 'source signals',
  },
  {
    v: 1,
    type: 'edge',
    id: 'state-guards-run',
    from: 'operating-state',
    to: 'generation-run',
    relation: 'guards',
    label: 'risk gates',
  },
  {
    v: 1,
    type: 'edge',
    id: 'run-generates-board',
    from: 'generation-run',
    to: 'generated-board',
    relation: 'generates',
    label: 'run output',
  },
  {
    v: 1,
    type: 'edge',
    id: 'board-feeds-evidence',
    from: 'generated-board',
    to: 'evidence-map',
    relation: 'feeds',
    label: 'claims',
  },
  {
    v: 1,
    type: 'edge',
    id: 'evidence-guards-review',
    from: 'evidence-map',
    to: 'review-queue',
    relation: 'guards',
    label: 'source trace',
  },
  {
    v: 1,
    type: 'edge',
    id: 'tools-feed-review',
    from: 'canvas-tools',
    to: 'review-queue',
    relation: 'feeds',
    label: 'workspace edits',
  },
  {
    v: 1,
    type: 'edge',
    id: 'review-validates-governance',
    from: 'review-queue',
    to: 'governance',
    relation: 'validates',
    label: 'approval',
  },
  {
    v: 1,
    type: 'edge',
    id: 'review-feeds-quality',
    from: 'review-queue',
    to: 'quality-bar',
    relation: 'feeds',
    label: 'findings',
  },
  {
    v: 1,
    type: 'edge',
    id: 'quality-guards-publish',
    from: 'quality-bar',
    to: 'publish-ready',
    relation: 'guards',
    label: 'quality gate',
  },
  {
    v: 1,
    type: 'edge',
    id: 'governance-extends-integrations',
    from: 'governance',
    to: 'integrations',
    relation: 'extends',
    label: 'policy metadata',
  },
  {
    v: 1,
    type: 'edge',
    id: 'integrations-feed-publish',
    from: 'integrations',
    to: 'publish-ready',
    relation: 'feeds',
    label: 'system handoff',
  },
] satisfies readonly CanvasStoryEvent[]
