import type { CanvasStoryEvent } from './CanvasStoryEvents'

export const DEMO_REPO_STORY_EVENTS = [
  {
    v: 1,
    type: 'section',
    id: 'engine',
    lane: 'architecture',
    title: 'Engine',
    purpose: 'Renderer-free canvas behavior contracts.',
  },
  {
    v: 1,
    type: 'card',
    id: 'engine-intent',
    sectionId: 'engine',
    role: 'module',
    title: 'Intent grammar',
    points: ['tool input', 'gesture state', 'command routing'],
  },
  {
    v: 1,
    type: 'card',
    id: 'engine-selection',
    sectionId: 'engine',
    role: 'module',
    title: 'Selection',
    points: ['click hit target', 'marquee overlap', 'resize handles'],
  },
  {
    v: 1,
    type: 'card',
    id: 'engine-overlay',
    sectionId: 'engine',
    role: 'contract',
    title: 'Overlay state',
    points: ['draft shape', 'snap guide', 'presence shape'],
  },
  {
    v: 1,
    type: 'table',
    id: 'engine-io',
    sectionId: 'engine',
    title: 'Engine I/O',
    columns: ['Input', 'Output'],
    rows: [
      ['Scene adapter', 'Hit + bounds'],
      ['Gesture input', 'Interaction'],
      ['Command', 'Result'],
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'app-workflow',
    lane: 'architecture',
    title: 'App Workflow',
    purpose: 'React state wiring without leaking assembly internals.',
  },
  {
    v: 1,
    type: 'card',
    id: 'app-assembly',
    sectionId: 'app-workflow',
    role: 'contract',
    title: 'Assembly seam',
    points: ['feature toggles', 'adapters', 'extensions'],
  },
  {
    v: 1,
    type: 'card',
    id: 'app-consumers',
    sectionId: 'app-workflow',
    role: 'workflow',
    title: 'Consumer fan-out',
    points: ['command', 'pointer', 'keyboard', 'viewport'],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'app-owns',
    sectionId: 'app-workflow',
    title: 'App owns',
    items: ['workflow hooks', 'runtime effects', 'control props', 'extension state'],
    checked: ['workflow hooks', 'control props'],
  },
  {
    v: 1,
    type: 'note',
    id: 'feature-toggle-note',
    sectionId: 'app-workflow',
    title: 'Toggle rule',
    body: 'Every affordance can disappear without corrupting the document.',
  },
  {
    v: 1,
    type: 'section',
    id: 'host-document',
    lane: 'architecture',
    title: 'Host Document',
    purpose: 'Demo data, storage, tree, validation, and read models.',
  },
  {
    v: 1,
    type: 'card',
    id: 'host-controller',
    sectionId: 'host-document',
    role: 'module',
    title: 'Document controller',
    points: ['history', 'clipboard', 'selection', 'patch commit'],
  },
  {
    v: 1,
    type: 'card',
    id: 'host-read-model',
    sectionId: 'host-document',
    role: 'contract',
    title: 'Read model',
    points: ['bounds lookup', 'tree traversal', 'scene adapter'],
  },
  {
    v: 1,
    type: 'table',
    id: 'host-contracts',
    sectionId: 'host-document',
    title: 'Storage shape',
    columns: ['Item', 'Owner', 'Rule'],
    rows: [
      ['Component', 'Host', 'stable id'],
      ['Custom', 'Product', 'JSON data'],
      ['Drawing', 'Host', 'canonical bounds'],
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'renderer',
    lane: 'architecture',
    title: 'Renderer Adapter',
    purpose: 'SVG stage and injected item layer, with no host ownership.',
  },
  {
    v: 1,
    type: 'card',
    id: 'renderer-stage',
    sectionId: 'renderer',
    role: 'module',
    title: 'Stage',
    points: ['viewport transform', 'grid', 'overlay layer'],
  },
  {
    v: 1,
    type: 'card',
    id: 'renderer-item-layer',
    sectionId: 'renderer',
    role: 'contract',
    title: 'Item layer adapter',
    points: ['host items in', 'SVG nodes out', 'pointer bridge'],
  },
  {
    v: 1,
    type: 'note',
    id: 'renderer-rule',
    sectionId: 'renderer',
    title: 'Renderer rule',
    body: 'It draws. It does not decide document meaning.',
  },
  {
    v: 1,
    type: 'section',
    id: 'ui-surfaces',
    lane: 'architecture',
    title: 'UI Surfaces',
    purpose: 'Toolbar, palettes, inspector, editor, and floating controls.',
  },
  {
    v: 1,
    type: 'card',
    id: 'toolbar-grammar',
    sectionId: 'ui-surfaces',
    role: 'control',
    title: 'Toolbar grammar',
    points: ['tool groups', 'command groups', 'custom actions'],
  },
  {
    v: 1,
    type: 'card',
    id: 'inspector-panels',
    sectionId: 'ui-surfaces',
    role: 'control',
    title: 'Inspector panels',
    points: ['bounds', 'style swatches', 'custom panels'],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'ui-minimalism',
    sectionId: 'ui-surfaces',
    title: 'Surface rule',
    items: ['No landing page', 'No decorative explainer', 'Controls only when useful'],
    checked: ['No landing page', 'Controls only when useful'],
  },
  {
    v: 1,
    type: 'section',
    id: 'llm-contract',
    lane: 'generation',
    title: 'LLM Contract',
    purpose: 'LLM emits meaning; canvas code emits geometry.',
  },
  {
    v: 1,
    type: 'card',
    id: 'event-not-item',
    sectionId: 'llm-contract',
    role: 'principle',
    title: 'Event, not item',
    points: ['no coordinates', 'no colors', 'no SVG details'],
  },
  {
    v: 1,
    type: 'card',
    id: 'json-schema',
    sectionId: 'llm-contract',
    role: 'guardrail',
    title: 'JSON Schema',
    points: ['enum fields', 'required keys', 'additional props blocked'],
  },
  {
    v: 1,
    type: 'table',
    id: 'event-types',
    sectionId: 'llm-contract',
    title: 'Story events',
    columns: ['Event', 'Meaning'],
    rows: [
      ['section', 'large region'],
      ['card', 'concept block'],
      ['edge', 'relationship'],
      ['table', 'matrix'],
    ],
  },
  {
    v: 1,
    type: 'note',
    id: 'small-output',
    sectionId: 'llm-contract',
    title: 'Small output',
    body: 'The model writes semantic facts. Layout density is generated.',
  },
  {
    v: 1,
    type: 'section',
    id: 'streaming',
    lane: 'generation',
    title: 'Streaming',
    purpose: 'One complete JSON event can be applied as soon as it arrives.',
  },
  {
    v: 1,
    type: 'card',
    id: 'sse-wire',
    sectionId: 'streaming',
    role: 'contract',
    title: 'SSE wire',
    points: ['event: canvas.story.delta', 'data: one JSON object'],
  },
  {
    v: 1,
    type: 'card',
    id: 'incremental-apply',
    sectionId: 'streaming',
    role: 'workflow',
    title: 'Incremental apply',
    points: ['parse event', 'append descriptor', 'regenerate board'],
  },
  {
    v: 1,
    type: 'risk',
    id: 'partial-json-risk',
    sectionId: 'streaming',
    title: 'Partial JSON',
    severity: 'High',
  },
  {
    v: 1,
    type: 'section',
    id: 'story-generator',
    lane: 'generation',
    title: 'Story Generator',
    purpose: 'Turns sparse domain events into a wide board.',
  },
  {
    v: 1,
    type: 'card',
    id: 'auto-layout',
    sectionId: 'story-generator',
    role: 'module',
    title: 'Auto layout',
    points: ['lanes', 'section packing', 'content grid'],
  },
  {
    v: 1,
    type: 'card',
    id: 'style-system',
    sectionId: 'story-generator',
    role: 'module',
    title: 'Style system',
    points: ['lane colors', 'role accents', 'relation strokes'],
  },
  {
    v: 1,
    type: 'checklist',
    id: 'generator-owns',
    sectionId: 'story-generator',
    title: 'Generator owns',
    items: ['position', 'size', 'connector side', 'component choice'],
    checked: ['position', 'size', 'connector side', 'component choice'],
  },
  {
    v: 1,
    type: 'section',
    id: 'user-flow',
    lane: 'workflow',
    title: 'Canvas Workflow',
    purpose: 'Known whiteboard actions remain built-in affordances.',
  },
  {
    v: 1,
    type: 'card',
    id: 'select-move',
    sectionId: 'user-flow',
    role: 'workflow',
    title: 'Select + move',
    points: ['single select', 'marquee', 'multi-item drag'],
  },
  {
    v: 1,
    type: 'card',
    id: 'create-edit',
    sectionId: 'user-flow',
    role: 'workflow',
    title: 'Create + edit',
    points: ['shape', 'sticky', 'text', 'inline editor'],
  },
  {
    v: 1,
    type: 'card',
    id: 'command-history',
    sectionId: 'user-flow',
    role: 'workflow',
    title: 'Command history',
    points: ['copy', 'duplicate', 'group', 'undo redo'],
  },
  {
    v: 1,
    type: 'table',
    id: 'workflow-map',
    sectionId: 'user-flow',
    title: 'Flow map',
    columns: ['Gesture', 'Module', 'Result'],
    rows: [
      ['Pointer down', 'Start session', 'interaction'],
      ['Pointer move', 'Preview', 'live item'],
      ['Pointer up', 'Lifecycle', 'commit'],
    ],
  },
  {
    v: 1,
    type: 'section',
    id: 'custom-modules',
    lane: 'extension',
    title: 'Custom Modules',
    purpose: 'Product meaning registers outside the built-in grammar.',
  },
  {
    v: 1,
    type: 'decision',
    id: 'decision-module',
    sectionId: 'custom-modules',
    title: 'Decision module',
    option: 'External descriptor owns product meaning',
    status: 'decided',
  },
  {
    v: 1,
    type: 'risk',
    id: 'risk-module',
    sectionId: 'custom-modules',
    title: 'Risk module',
    severity: 'Medium',
  },
  {
    v: 1,
    type: 'checklist',
    id: 'module-slots',
    sectionId: 'custom-modules',
    title: 'Descriptor slots',
    items: ['creation tool', 'renderer', 'validator', 'inspector', 'command'],
    checked: ['creation tool', 'renderer', 'validator', 'inspector', 'command'],
  },
  {
    v: 1,
    type: 'card',
    id: 'extension-boundary',
    sectionId: 'custom-modules',
    role: 'contract',
    title: 'Boundary',
    points: ['internal grammar stays stable', 'product meaning plugs in'],
  },
  {
    v: 1,
    type: 'section',
    id: 'guardrails',
    lane: 'quality',
    title: 'Guardrails',
    purpose: 'Tests and product rules keep the part factory coherent.',
  },
  {
    v: 1,
    type: 'card',
    id: 'architecture-tests',
    sectionId: 'guardrails',
    role: 'guardrail',
    title: 'Architecture tests',
    points: ['import seams', 'public facades', 'folder boundaries'],
  },
  {
    v: 1,
    type: 'card',
    id: 'demo-rule',
    sectionId: 'guardrails',
    role: 'principle',
    title: 'Demo rule',
    points: ['minimal explanation', 'minimal decoration', 'real controls'],
  },
  {
    v: 1,
    type: 'table',
    id: 'guardrail-table',
    sectionId: 'guardrails',
    title: 'Regression catch',
    columns: ['Guardrail', 'Catches'],
    rows: [
      ['package facade', 'deep imports'],
      ['assembly contract', 'bad adapters'],
      ['custom module', 'invalid descriptors'],
    ],
  },
  {
    v: 1,
    type: 'edge',
    id: 'engine-feeds-app',
    from: 'engine',
    to: 'app-workflow',
    relation: 'feeds',
    label: 'behavior contract',
  },
  {
    v: 1,
    type: 'edge',
    id: 'app-owns-host',
    from: 'app-workflow',
    to: 'host-document',
    relation: 'owns',
    label: 'document runtime',
  },
  {
    v: 1,
    type: 'edge',
    id: 'app-renders-renderer',
    from: 'app-workflow',
    to: 'renderer',
    relation: 'renders',
    label: 'adapter input',
  },
  {
    v: 1,
    type: 'edge',
    id: 'ui-feeds-app',
    from: 'ui-surfaces',
    to: 'app-workflow',
    relation: 'feeds',
    label: 'commands',
  },
  {
    v: 1,
    type: 'edge',
    id: 'contract-feeds-stream',
    from: 'llm-contract',
    to: 'streaming',
    relation: 'feeds',
    label: 'event objects',
  },
  {
    v: 1,
    type: 'edge',
    id: 'stream-feeds-generator',
    from: 'streaming',
    to: 'story-generator',
    relation: 'generates',
    label: 'deltas',
  },
  {
    v: 1,
    type: 'edge',
    id: 'generator-renders-board',
    from: 'story-generator',
    to: 'renderer',
    relation: 'renders',
    label: 'CanvasItem[]',
  },
  {
    v: 1,
    type: 'edge',
    id: 'custom-extends-app',
    from: 'custom-modules',
    to: 'app-workflow',
    relation: 'extends',
    label: 'extension bundle',
  },
  {
    v: 1,
    type: 'edge',
    id: 'guardrails-guard-app',
    from: 'guardrails',
    to: 'app-workflow',
    relation: 'guards',
    label: 'tests',
  },
] satisfies readonly CanvasStoryEvent[]
