import {
  getCanvasAppFeaturePackInstallPlan,
  getCanvasAppFeaturePackPartialUpdatePlan,
  getCanvasAppFeaturePackStateTransitionPlan,
  type CanvasAppFeaturePackInstallPlan,
  type CanvasAppFeaturePackInstallPlanBlockedReason,
  type CanvasAppFeaturePackInstallPlanConflictReason,
  type CanvasAppFeaturePackInstallPlanConflictScope,
  type CanvasAppFeaturePackInstallPlanInput,
  type CanvasAppFeaturePackInstallPlanMissingRequiredReason,
  type CanvasAppFeaturePackInstallPlanMode,
  type CanvasAppFeaturePackInstallPlanStatus,
  type CanvasAppFeaturePackInstallPlanUnknownTargetReason,
  type CanvasAppFeaturePackMarketplaceActionKind,
  type CanvasAppFeaturePackPartialUpdateOperation,
  type CanvasAppFeaturePackPartialUpdatePlan,
  type CanvasAppFeaturePackPartialUpdatePlanBlockedReason,
  type CanvasAppFeaturePackPartialUpdatePlanEmptySurfaceReason,
  type CanvasAppFeaturePackPartialUpdatePlanEntry,
  type CanvasAppFeaturePackPartialUpdatePlanInput,
  type CanvasAppFeaturePackPartialUpdatePlanOperationUnavailableReason,
  type CanvasAppFeaturePackPartialUpdatePlanStatus,
  type CanvasAppFeaturePackPartialUpdatePlanUnknownTargetReason,
  type CanvasAppFeaturePackStateTransitionBlockedReason,
  type CanvasAppFeaturePackStateTransitionChange,
  type CanvasAppFeaturePackStateTransitionDependencyReason,
  type CanvasAppFeaturePackStateTransitionInstallPlanReason,
  type CanvasAppFeaturePackStateTransitionLifecycleReason,
  type CanvasAppFeaturePackStateTransitionOperation,
  type CanvasAppFeaturePackStateTransitionPartialUpdateReason,
  type CanvasAppFeaturePackStateTransitionPlan,
  type CanvasAppFeaturePackStateTransitionPlanInput,
  type CanvasAppFeaturePackStateTransitionPlanStatus,
  type CanvasAppFeaturePackStateTransitionUninstallPolicyEntry,
  type CanvasAppFeaturePackStateTransitionUnknownTargetReason,
} from '../app/feature-packs'
import {
  CANVAS_APP_FEATURE_PACK_MARKETPLACE_ACTION_KINDS,
} from '../app/feature-packs/CanvasAppFeaturePackActionContracts'
import {
  isCanvasAppFeaturePackStateTransitionOperation,
} from '../app/feature-packs/CanvasAppFeaturePackStateTransitionPlanContracts'

export const CANVAS_MARKETPLACE_FEATURE_PACK_ACTION_KINDS =
  CANVAS_APP_FEATURE_PACK_MARKETPLACE_ACTION_KINDS
export const getCanvasMarketplaceFeaturePackInstallPlan =
  getCanvasAppFeaturePackInstallPlan
export const getCanvasMarketplaceFeaturePackPartialUpdatePlan =
  getCanvasAppFeaturePackPartialUpdatePlan
export const getCanvasMarketplaceFeaturePackStateTransitionPlan =
  getCanvasAppFeaturePackStateTransitionPlan
export const isCanvasMarketplaceFeaturePackStateTransitionOperation =
  isCanvasAppFeaturePackStateTransitionOperation

export type CanvasMarketplaceFeaturePackInstallPlan =
  CanvasAppFeaturePackInstallPlan
export type CanvasMarketplaceFeaturePackInstallPlanBlockedReason =
  CanvasAppFeaturePackInstallPlanBlockedReason
export type CanvasMarketplaceFeaturePackInstallPlanConflictReason =
  CanvasAppFeaturePackInstallPlanConflictReason
export type CanvasMarketplaceFeaturePackInstallPlanConflictScope =
  CanvasAppFeaturePackInstallPlanConflictScope
export type CanvasMarketplaceFeaturePackInstallPlanInput =
  CanvasAppFeaturePackInstallPlanInput
export type CanvasMarketplaceFeaturePackInstallPlanMissingRequiredReason =
  CanvasAppFeaturePackInstallPlanMissingRequiredReason
export type CanvasMarketplaceFeaturePackInstallPlanMode =
  CanvasAppFeaturePackInstallPlanMode
export type CanvasMarketplaceFeaturePackInstallPlanStatus =
  CanvasAppFeaturePackInstallPlanStatus
export type CanvasMarketplaceFeaturePackInstallPlanUnknownTargetReason =
  CanvasAppFeaturePackInstallPlanUnknownTargetReason
export type CanvasMarketplaceFeaturePackActionKind =
  CanvasAppFeaturePackMarketplaceActionKind
export type CanvasMarketplaceFeaturePackPartialUpdateOperation =
  CanvasAppFeaturePackPartialUpdateOperation
export type CanvasMarketplaceFeaturePackPartialUpdatePlan =
  CanvasAppFeaturePackPartialUpdatePlan
export type CanvasMarketplaceFeaturePackPartialUpdatePlanBlockedReason =
  CanvasAppFeaturePackPartialUpdatePlanBlockedReason
export type CanvasMarketplaceFeaturePackPartialUpdatePlanEmptySurfaceReason =
  CanvasAppFeaturePackPartialUpdatePlanEmptySurfaceReason
export type CanvasMarketplaceFeaturePackPartialUpdatePlanEntry =
  CanvasAppFeaturePackPartialUpdatePlanEntry
export type CanvasMarketplaceFeaturePackPartialUpdatePlanInput =
  CanvasAppFeaturePackPartialUpdatePlanInput
export type CanvasMarketplaceFeaturePackPartialUpdatePlanOperationUnavailableReason =
  CanvasAppFeaturePackPartialUpdatePlanOperationUnavailableReason
export type CanvasMarketplaceFeaturePackPartialUpdatePlanStatus =
  CanvasAppFeaturePackPartialUpdatePlanStatus
export type CanvasMarketplaceFeaturePackPartialUpdatePlanUnknownTargetReason =
  CanvasAppFeaturePackPartialUpdatePlanUnknownTargetReason
export type CanvasMarketplaceFeaturePackStateTransitionBlockedReason =
  CanvasAppFeaturePackStateTransitionBlockedReason
export type CanvasMarketplaceFeaturePackStateTransitionChange =
  CanvasAppFeaturePackStateTransitionChange
export type CanvasMarketplaceFeaturePackStateTransitionDependencyReason =
  CanvasAppFeaturePackStateTransitionDependencyReason
export type CanvasMarketplaceFeaturePackStateTransitionInstallPlanReason =
  CanvasAppFeaturePackStateTransitionInstallPlanReason
export type CanvasMarketplaceFeaturePackStateTransitionLifecycleReason =
  CanvasAppFeaturePackStateTransitionLifecycleReason
export type CanvasMarketplaceFeaturePackStateTransitionOperation =
  CanvasAppFeaturePackStateTransitionOperation
export type CanvasMarketplaceFeaturePackStateTransitionPartialUpdateReason =
  CanvasAppFeaturePackStateTransitionPartialUpdateReason
export type CanvasMarketplaceFeaturePackStateTransitionPlan =
  CanvasAppFeaturePackStateTransitionPlan
export type CanvasMarketplaceFeaturePackStateTransitionPlanInput =
  CanvasAppFeaturePackStateTransitionPlanInput
export type CanvasMarketplaceFeaturePackStateTransitionPlanStatus =
  CanvasAppFeaturePackStateTransitionPlanStatus
export type CanvasMarketplaceFeaturePackStateTransitionUninstallPolicyEntry =
  CanvasAppFeaturePackStateTransitionUninstallPolicyEntry
export type CanvasMarketplaceFeaturePackStateTransitionUnknownTargetReason =
  CanvasAppFeaturePackStateTransitionUnknownTargetReason
