import type { CanvasItem } from '../canvas'

export const DEMO_CANVAS_INITIAL_SELECTION = ['engine-shape']

export const DEMO_CANVAS_REFERENCE_BOUNDS = {
  h: 540,
  w: 900,
  x: 72,
  y: 72,
}

const DEMO_CANVAS_IMAGE_SRC = [
  'data:image/svg+xml;base64,',
  'PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyNDAi',
  'IGhlaWdodD0iMTUwIiB2aWV3Qm94PSIwIDAgMjQwIDE1MCI+PHJlY3Qgd2lkdGg9',
  'IjI0MCIgaGVpZ2h0PSIxNTAiIHJ4PSIxNiIgZmlsbD0iI2VlZjJmNyIvPjxyZWN0',
  'IHg9IjIyIiB5PSIyMiIgd2lkdGg9IjE5NiIgaGVpZ2h0PSIxMDYiIHJ4PSIxMCIg',
  'ZmlsbD0iI2ZmZmZmZiIgc3Ryb2tlPSIjOTRhM2I4IiBzdHJva2Utd2lkdGg9IjIi',
  'Lz48Y2lyY2xlIGN4PSI1OCIgY3k9IjU4IiByPSIxNiIgZmlsbD0iIzM4YmRmOCIv',
  'PjxwYXRoIGQ9Ik0zOCAxMTIgTDkyIDc4IEwxMjYgMTAyIEwxNjAgNzAgTDIwNiAx',
  'MTIgWiIgZmlsbD0iIzY0NzQ4YiIgb3BhY2l0eT0iMC44NSIvPjwvc3ZnPg==',
].join('')

export const DEMO_CANVAS_SEED_ITEMS: CanvasItem[] = [
  {
    accent: '#2563eb',
    body: '',
    component: 'section',
    fill: '#f8fafc',
    h: 510,
    id: 'engine-section',
    stroke: '#94a3b8',
    title: 'Canvas affordance loop',
    type: 'component',
    w: 878,
    x: 72,
    y: 72,
  },
  {
    fill: '#f8fafc',
    h: 104,
    id: 'engine-shape',
    shapeType: 'rect',
    stroke: '#334155',
    text: 'Shape',
    type: 'shape',
    w: 148,
    x: 126,
    y: 344,
  },
  {
    accent: '#ca8a04',
    body: 'Post-it',
    component: 'sticky',
    fill: '#fef3c7',
    h: 132,
    id: 'engine-sticky',
    stroke: '#eab308',
    title: '',
    type: 'component',
    w: 164,
    x: 126,
    y: 142,
  },
  {
    accent: '#16a34a',
    body: 'Quick create',
    component: 'sticky',
    fill: '#dcfce7',
    h: 132,
    id: 'engine-sticky-next',
    stroke: '#86efac',
    title: '',
    type: 'component',
    w: 164,
    x: 360,
    y: 142,
  },
  {
    accent: '#2563eb',
    body: 'Note',
    component: 'sticky',
    fill: '#dbeafe',
    h: 132,
    id: 'engine-sticky-note',
    stroke: '#93c5fd',
    title: '',
    type: 'component',
    w: 164,
    x: 594,
    y: 142,
  },
  {
    fill: '#ecfeff',
    h: 104,
    id: 'engine-ellipse',
    shapeType: 'ellipse',
    stroke: '#0891b2',
    text: 'Variant',
    type: 'shape',
    w: 148,
    x: 328,
    y: 344,
  },
  {
    fill: '#f5f3ff',
    h: 104,
    id: 'engine-diamond',
    shapeType: 'diamond',
    stroke: '#7c3aed',
    text: 'Decision',
    type: 'shape',
    w: 148,
    x: 530,
    y: 344,
  },
  {
    h: 72,
    id: 'engine-text',
    text: 'Text editing',
    type: 'text',
    w: 164,
    x: 762,
    y: 148,
  },
  {
    end: { x: 360, y: 208 },
    endAttachedTo: 'engine-sticky-next',
    h: 32,
    id: 'engine-arrow',
    routing: 'elbow',
    start: { x: 290, y: 208 },
    startAttachedTo: 'engine-sticky',
    stroke: '#334155',
    strokeWidth: 2.5,
    text: 'Flow',
    type: 'arrow',
    w: 70,
    x: 290,
    y: 192,
  },
  {
    end: { x: 594, y: 208 },
    endAttachedTo: 'engine-sticky-note',
    h: 32,
    id: 'engine-arrow-note',
    routing: 'straight',
    start: { x: 524, y: 208 },
    startAttachedTo: 'engine-sticky-next',
    stroke: '#334155',
    strokeWidth: 2.5,
    text: '',
    type: 'arrow',
    w: 70,
    x: 524,
    y: 192,
  },
  {
    h: 74,
    id: 'engine-drawing',
    opacity: 1,
    points: [
      { x: 126, y: 520 },
      { x: 218, y: 468 },
      { x: 314, y: 520 },
      { x: 410, y: 468 },
      { x: 530, y: 510 },
    ],
    stroke: '#475569',
    strokeWidth: 5,
    type: 'marker',
    w: 404,
    x: 126,
    y: 468,
  },
  {
    h: 54,
    id: 'engine-highlight',
    opacity: 0.42,
    points: [
      { x: 126, y: 494 },
      { x: 250, y: 468 },
      { x: 376, y: 492 },
      { x: 512, y: 468 },
    ],
    stroke: '#fde047',
    strokeWidth: 18,
    type: 'highlight',
    w: 386,
    x: 126,
    y: 459,
  },
  {
    alt: 'Canvas image object',
    h: 110,
    id: 'engine-image',
    mimeType: 'image/svg+xml',
    name: 'asset.svg',
    naturalHeight: 150,
    naturalWidth: 240,
    src: DEMO_CANVAS_IMAGE_SRC,
    type: 'image',
    w: 176,
    x: 748,
    y: 336,
  },
  {
    h: 32,
    id: 'engine-stamp-yes',
    label: '+1',
    stamp: 'thumbs-up',
    type: 'stamp',
    w: 32,
    x: 732,
    y: 124,
  },
  {
    h: 32,
    id: 'engine-stamp-question',
    label: '?',
    stamp: 'question',
    type: 'stamp',
    w: 32,
    x: 770,
    y: 124,
  },
]
