import type { CanvasItem } from '../canvas'

export const DEMO_CANVAS_SEED_ITEMS: CanvasItem[] = [
  {
    id: 'demo-frame',
    type: 'component',
    component: 'section',
    title: 'Decision flow',
    body: '',
    x: 72,
    y: 96,
    w: 760,
    h: 360,
    fill: 'rgba(241, 245, 249, 0.34)',
    stroke: '#94a3b8',
    accent: '#64748b',
  },
  {
    id: 'demo-context',
    type: 'component',
    component: 'sticky',
    title: 'Context',
    body: 'Renewal scope',
    x: 116,
    y: 136,
    w: 188,
    h: 128,
    fill: '#fef3c7',
    stroke: '#eab308',
    accent: '#ca8a04',
  },
  {
    id: 'demo-decision',
    type: 'custom',
    kind: 'decision',
    presentation: 'decision-node',
    title: 'Decision',
    data: {
      option: 'Approve pilot',
      status: 'proposed',
    },
    x: 352,
    y: 140,
    w: 230,
    h: 116,
  },
  {
    id: 'demo-risk',
    type: 'custom',
    kind: 'risk',
    presentation: 'risk-node',
    title: 'Risk',
    data: {
      severity: 'High',
    },
    x: 628,
    y: 152,
    w: 176,
    h: 92,
  },
  {
    id: 'demo-connector',
    type: 'component',
    component: 'connector',
    title: '',
    x: 582,
    y: 172,
    w: 58,
    h: 42,
    fill: 'transparent',
    stroke: '#475569',
    accent: '#475569',
  },
  {
    id: 'demo-next',
    type: 'component',
    component: 'checklist',
    title: 'Next',
    checkedItems: [0],
    items: ['Owner', 'Date', 'Review'],
    x: 116,
    y: 304,
    w: 214,
    h: 136,
    fill: '#ffffff',
    stroke: '#cbd5e1',
    accent: '#16a34a',
  },
  {
    id: 'demo-score',
    type: 'component',
    component: 'table',
    title: 'Score',
    columns: ['Impact', 'Effort'],
    items: ['High', 'Med'],
    x: 408,
    y: 312,
    w: 240,
    h: 112,
    fill: '#ffffff',
    stroke: '#cbd5e1',
    accent: '#0891b2',
  },
]
