import type {
  DesignJSONObject,
  DesignNode,
  DesignNodeComponentBinding,
} from '@interactive-os/canvas/react-design'
import {
  createFigmaDesignNodeLayout,
  createFigmaDesignNodeStyle,
  normalizeFigmaDesignNodeState,
  type FigmaDesignNodeState,
} from './FigmaDesignDocumentSeedTypes'

type FigmaHomeNodeSeed = readonly [
  id: string,
  parentId: string | null,
  intrinsic: string,
  label: string,
]

const HOME_NODE_SEEDS = [
  ['homePage', null, 'section', 'Editorial homepage'],
  ['homeHeader', 'homePage', 'header', 'Header'],
  ['homeBrand', 'homeHeader', 'div', 'Brand'],
  ['homeBrandMark', 'homeBrand', 'div', 'Logo mark'],
  ['homeBrandText', 'homeBrand', 'strong', 'Logo text'],
  ['homeNav', 'homeHeader', 'nav', 'Primary nav'],
  ['homeNavEssays', 'homeNav', 'button', 'Essays link'],
  ['homeNavMethods', 'homeNav', 'button', 'Methods link'],
  ['homeNavArchive', 'homeNav', 'button', 'Archive link'],
  ['homeSubscribe', 'homeHeader', 'div', 'Subscribe CTA'],
  ['homeSubscribeLabel', 'homeSubscribe', 'strong', 'CTA label'],
  ['homeSubscribeNote', 'homeSubscribe', 'span', 'CTA note'],
  ['homeMain', 'homePage', 'main', 'Page body'],
  ['homeIssueRail', 'homeMain', 'section', 'Issue rail'],
  ['homeIssueKicker', 'homeIssueRail', 'span', 'Issue kicker'],
  ['homeIssueTitle', 'homeIssueRail', 'div', 'Issue title'],
  ['homeIssueTime', 'homeIssueRail', 'button', 'Read time'],
  ['homeHero', 'homeMain', 'section', 'Hero article'],
  ['homeHeroCopy', 'homeHero', 'div', 'Hero copy'],
  ['homeHeroTitle', 'homeHeroCopy', 'h1', 'Hero title'],
  ['homeHeroText', 'homeHeroCopy', 'p', 'Hero dek'],
  ['homeHeroActions', 'homeHero', 'div', 'Hero actions'],
  ['homePrimaryAction', 'homeHeroActions', 'button', 'Primary action'],
  ['homeSecondaryAction', 'homeHeroActions', 'button', 'Secondary action'],
  ['homeMeta', 'homeMain', 'section', 'Article meta'],
  ['homeByline', 'homeMeta', 'article', 'Byline'],
  ['homeBylineLabel', 'homeByline', 'span', 'Byline label'],
  ['homeBylineValue', 'homeByline', 'strong', 'Author name'],
  ['homeBylineNote', 'homeByline', 'em', 'Author note'],
  ['homeCategory', 'homeMeta', 'article', 'Category'],
  ['homeCategoryLabel', 'homeCategory', 'span', 'Category label'],
  ['homeCategoryValue', 'homeCategory', 'strong', 'Category name'],
  ['homeCategoryNote', 'homeCategory', 'em', 'Category note'],
  ['homeReadTime', 'homeMeta', 'article', 'Reading time'],
  ['homeReadTimeLabel', 'homeReadTime', 'span', 'Time label'],
  ['homeReadTimeValue', 'homeReadTime', 'strong', 'Time value'],
  ['homeReadTimeNote', 'homeReadTime', 'em', 'Time note'],
  ['homeArticle', 'homeMain', 'section', 'Article preview'],
  ['homeEssay', 'homeArticle', 'article', 'Essay body'],
  ['homeEssayHeading', 'homeEssay', 'h2', 'Body heading'],
  ['homeChapterList', 'homeEssay', 'div', 'Chapter list'],
  ['homeChapterOne', 'homeChapterList', 'article', 'Chapter 1'],
  ['homeChapterOneTitle', 'homeChapterOne', 'strong', 'Chapter title 1'],
  ['homeChapterOneNumber', 'homeChapterOne', 'span', 'Chapter number 1'],
  ['homeChapterTwo', 'homeChapterList', 'article', 'Chapter 2'],
  ['homeChapterTwoTitle', 'homeChapterTwo', 'strong', 'Chapter title 2'],
  ['homeChapterTwoNumber', 'homeChapterTwo', 'span', 'Chapter number 2'],
  ['homeChapterThree', 'homeChapterList', 'article', 'Chapter 3'],
  ['homeChapterThreeTitle', 'homeChapterThree', 'strong', 'Chapter title 3'],
  ['homeChapterThreeNumber', 'homeChapterThree', 'span', 'Chapter number 3'],
  ['homeQuote', 'homeArticle', 'aside', 'Pull quote'],
  ['homeQuoteHeading', 'homeQuote', 'h2', 'Quote heading'],
  ['homeQuoteList', 'homeQuote', 'div', 'Quote lines'],
  ['homeQuoteOne', 'homeQuoteList', 'article', 'Quote line 1'],
  ['homeQuoteOneText', 'homeQuoteOne', 'span', 'Quote text 1'],
  ['homeQuoteTwo', 'homeQuoteList', 'article', 'Quote line 2'],
  ['homeQuoteTwoText', 'homeQuoteTwo', 'span', 'Quote text 2'],
  ['homeQuoteThree', 'homeQuoteList', 'article', 'Quote line 3'],
  ['homeQuoteThreeText', 'homeQuoteThree', 'span', 'Quote text 3'],
  ['homeDispatches', 'homeMain', 'section', 'Dispatches'],
  ['homeDispatchHeading', 'homeDispatches', 'h2', 'Dispatch heading'],
  ['homeDispatchGrid', 'homeDispatches', 'div', 'Dispatch grid'],
  ['homeDispatchOne', 'homeDispatchGrid', 'article', 'Dispatch card 1'],
  ['homeDispatchOneTitle', 'homeDispatchOne', 'strong', 'Dispatch title 1'],
  ['homeDispatchOneText', 'homeDispatchOne', 'p', 'Dispatch text 1'],
  ['homeDispatchTwo', 'homeDispatchGrid', 'article', 'Dispatch card 2'],
  ['homeDispatchTwoTitle', 'homeDispatchTwo', 'strong', 'Dispatch title 2'],
  ['homeDispatchTwoText', 'homeDispatchTwo', 'p', 'Dispatch text 2'],
  ['homeDispatchThree', 'homeDispatchGrid', 'article', 'Dispatch card 3'],
  ['homeDispatchThreeTitle', 'homeDispatchThree', 'strong', 'Dispatch title 3'],
  ['homeDispatchThreeText', 'homeDispatchThree', 'p', 'Dispatch text 3'],
  ['homeNewsletter', 'homeMain', 'section', 'Newsletter band'],
  ['homeNewsletterHeading', 'homeNewsletter', 'h2', 'Newsletter heading'],
  ['homeNewsletterText', 'homeNewsletter', 'p', 'Newsletter text'],
  ['homeNewsletterAction', 'homeNewsletter', 'button', 'Newsletter action'],
  ['homeFooter', 'homeMain', 'footer', 'Footer'],
  ['homeFooterBrand', 'homeFooter', 'strong', 'Footer brand'],
  ['homeFooterNote', 'homeFooter', 'span', 'Footer note'],
] as const satisfies readonly FigmaHomeNodeSeed[]

export type FigmaHomeDesignNodeId = typeof HOME_NODE_SEEDS[number][0]
export type FigmaHomeComponentDefinitionId = 'home-meta-card'

export type FigmaHomeComponentMetadata = {
  readonly id: FigmaHomeComponentDefinitionId
  readonly instances: readonly {
    readonly id: string
    readonly label: string
    readonly slots: Readonly<Record<string, FigmaHomeDesignNodeId>>
  }[]
  readonly label: string
  readonly source: {
    readonly exportName: string
    readonly importPath: string
    readonly layer: 'shared'
  }
  readonly syncDescription: string
}

export const FIGMA_HOME_COMPONENT_METADATA = [{
  id: 'home-meta-card',
  label: 'Article meta card',
  source: {
    exportName: 'ArticleMetaCard',
    importPath: 'src/shared/article-meta-card',
    layer: 'shared',
  },
  syncDescription: 'Layout and style edits sync across meta card instances.',
  instances: [
    {
      id: 'homeByline',
      label: 'Byline',
      slots: {
        label: 'homeBylineLabel',
        note: 'homeBylineNote',
        root: 'homeByline',
        value: 'homeBylineValue',
      },
    },
    {
      id: 'homeCategory',
      label: 'Category',
      slots: {
        label: 'homeCategoryLabel',
        note: 'homeCategoryNote',
        root: 'homeCategory',
        value: 'homeCategoryValue',
      },
    },
    {
      id: 'homeReadTime',
      label: 'Reading time',
      slots: {
        label: 'homeReadTimeLabel',
        note: 'homeReadTimeNote',
        root: 'homeReadTime',
        value: 'homeReadTimeValue',
      },
    },
  ],
}] as const satisfies readonly FigmaHomeComponentMetadata[]

const HOME_CLASS_NAMES: Partial<Record<FigmaHomeDesignNodeId, string>> = {
  homePage: 'figma-dom-home',
  homeHeader: 'figma-dom-home__header',
  homeBrand: 'figma-dom-home__brand',
  homeBrandMark: 'figma-dom-home__brand-mark',
  homeBrandText: 'figma-dom-home__brand-text',
  homeNav: 'figma-dom-home__nav',
  homeNavEssays:
    'figma-dom-home__nav-item figma-dom-home__nav-item--active',
  homeNavMethods: 'figma-dom-home__nav-item',
  homeNavArchive: 'figma-dom-home__nav-item',
  homeSubscribe: 'figma-dom-home__subscribe',
  homeMain: 'figma-dom-home__main',
  homeIssueRail: 'figma-dom-home__issue',
  homeIssueTime: 'figma-dom-home__time',
  homeHero: 'figma-dom-home__hero',
  homeHeroCopy: 'figma-dom-home__hero-copy',
  homeHeroActions: 'figma-dom-home__hero-actions',
  homePrimaryAction: 'figma-dom-home__primary',
  homeSecondaryAction: 'figma-dom-home__secondary',
  homeMeta: 'figma-dom-home__meta',
  homeByline: 'figma-dom-home__meta-item',
  homeCategory: 'figma-dom-home__meta-item',
  homeReadTime: 'figma-dom-home__meta-item',
  homeArticle: 'figma-dom-home__article',
  homeEssay: 'figma-dom-home__essay',
  homeChapterList: 'figma-dom-home__chapters',
  homeChapterOne: 'figma-dom-home__chapter',
  homeChapterTwo: 'figma-dom-home__chapter',
  homeChapterThree: 'figma-dom-home__chapter',
  homeQuote: 'figma-dom-home__quote',
  homeQuoteList: 'figma-dom-home__quote-list',
  homeQuoteOne: 'figma-dom-home__quote-line',
  homeQuoteTwo: 'figma-dom-home__quote-line',
  homeQuoteThree: 'figma-dom-home__quote-line',
  homeDispatches: 'figma-dom-home__dispatches',
  homeDispatchGrid: 'figma-dom-home__dispatch-grid',
  homeDispatchOne: 'figma-dom-home__dispatch',
  homeDispatchTwo: 'figma-dom-home__dispatch',
  homeDispatchThree: 'figma-dom-home__dispatch',
  homeNewsletter: 'figma-dom-home__newsletter',
  homeNewsletterAction: 'figma-dom-home__newsletter-action',
  homeFooter: 'figma-dom-home__footer',
}

const HOME_TEXT = {
  homeBrandMark: 'C',
  homeBrandText: 'Canvas Review',
  homeBylineLabel: 'Written by',
  homeBylineNote: 'Design systems editor',
  homeBylineValue: 'Lina Kim',
  homeCategoryLabel: 'Filed under',
  homeCategoryNote: 'Interfaces, layout, copy',
  homeCategoryValue: 'Product craft',
  homeChapterOneNumber: '01',
  homeChapterOneTitle: 'Start with the lead, not the module',
  homeChapterThreeNumber: '03',
  homeChapterThreeTitle: 'Retouch inside the real viewport',
  homeChapterTwoNumber: '02',
  homeChapterTwoTitle: 'Let spacing carry the argument',
  homeDispatchHeading: 'More from the issue',
  homeDispatchOneText:
    'How component affordances change when the page is the source of truth.',
  homeDispatchOneTitle: 'The editor is a viewport',
  homeDispatchThreeText:
    'A compact guide to deciding what belongs in a panel and what belongs on canvas.',
  homeDispatchThreeTitle: 'Panel last, canvas first',
  homeDispatchTwoText:
    'Why final retouching needs distance, baseline, and spacing cues together.',
  homeDispatchTwoTitle: 'Measuring the rhythm',
  homeEssayHeading: 'When the page becomes the editor',
  homeFooterBrand: 'Canvas Review',
  homeFooterNote:
    'Independent notes on design tooling, DOM layout, and editorial interfaces.',
  homeHeroText:
    'A field note on turning layout controls into editorial rhythm: headline, dek, metadata, quote, body, dispatches, newsletter, and footer all editable in place.',
  homeHeroTitle: 'The homepage is an article before it is an interface',
  homeIssueKicker: 'Field essay',
  homeIssueTime: '12 min',
  homeIssueTitle: 'Issue 04 - Design after the mockup',
  homeNavArchive: 'Archive',
  homeNavEssays: 'Essays',
  homeNavMethods: 'Methods',
  homeNewsletterAction: 'Join weekly',
  homeNewsletterHeading: 'Receive the next field note',
  homeNewsletterText:
    'A short weekly note on interface craft, layout semantics, and the last mile of design editing.',
  homePrimaryAction: 'Read essay',
  homeQuoteHeading: "Editor's note",
  homeQuoteOneText: 'A homepage can read like a lead paragraph.',
  homeQuoteThreeText: 'The last retouch belongs in the viewport.',
  homeQuoteTwoText: 'Spacing is part of the argument, not decoration.',
  homeReadTimeLabel: 'Reading time',
  homeReadTimeNote: 'Updated Jun 2026',
  homeReadTimeValue: '12 minutes',
  homeSecondaryAction: 'Save note',
  homeSubscribeLabel: 'Subscribe',
  homeSubscribeNote: 'Weekly',
} as const satisfies Partial<Record<FigmaHomeDesignNodeId, string>>

const EMPTY_STATE: FigmaDesignNodeState = {
  align: 'stretch',
  alignSelf: 'auto',
  direction: 'column',
  distribution: 'packed',
  gap: 0,
  h: 0,
  heightMode: 'fixed',
  margin: 0,
  opacity: 100,
  order: 0,
  padding: 0,
  paddingBottom: 0,
  paddingLeft: 0,
  paddingRight: 0,
  paddingTop: 0,
  radius: 0,
  rotation: 0,
  w: 0,
  widthMode: 'fixed',
  x: 0,
  y: 0,
}

const FIXED_BOX_LAYOUT = {
  align: 'stretch',
  alignSelf: 'auto',
  direction: 'column',
  distribution: 'packed',
  heightMode: 'fixed',
  widthMode: 'fixed',
} as const

const HUG_AUTO_LAYOUT_FRAME = {
  align: 'stretch',
  alignSelf: 'auto',
  direction: 'column',
  distribution: 'packed',
  heightMode: 'hug',
  widthMode: 'hug',
} as const

const HUG_BOX_LAYOUT = HUG_AUTO_LAYOUT_FRAME

const TEXT_LEAF_STATE: FigmaDesignNodeState = {
  ...EMPTY_STATE,
  ...HUG_BOX_LAYOUT,
  h: 18,
  w: 80,
}

const HOME_NODE_STATES = mapHomeNodeStates({
  homePage: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'stretch',
    direction: 'column',
    h: 1736,
    w: 1180,
    widthMode: 'fill',
  },
  homeHeader: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    gap: 28,
    h: 88,
    padding: 42,
    w: 1180,
    widthMode: 'fill',
  },
  homeBrand: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    gap: 12,
    h: 32,
    w: 168,
  },
  homeBrandMark: {
    ...EMPTY_STATE,
    ...FIXED_BOX_LAYOUT,
    h: 28,
    radius: 8,
    w: 28,
  },
  homeBrandText: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 22,
    w: 122,
  },
  homeNav: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    gap: 18,
    h: 36,
    w: 310,
  },
  homeNavEssays: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 32,
    padding: 8,
    radius: 16,
    w: 74,
  },
  homeNavMethods: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 32,
    padding: 8,
    radius: 16,
    w: 86,
  },
  homeNavArchive: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 32,
    padding: 8,
    radius: 16,
    w: 78,
  },
  homeSubscribe: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    gap: 10,
    h: 38,
    padding: 12,
    radius: 18,
    w: 158,
  },
  homeSubscribeLabel: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 18,
    w: 72,
  },
  homeSubscribeNote: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 18,
    w: 48,
  },
  homeMain: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    h: 1648,
    w: 1180,
    widthMode: 'fill',
  },
  homeIssueRail: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    gap: 18,
    h: 72,
    padding: 42,
    w: 1180,
    widthMode: 'fill',
  },
  homeIssueKicker: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 22,
    w: 104,
  },
  homeIssueTitle: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 34,
    padding: 10,
    radius: 17,
    w: 460,
    widthMode: 'fill',
  },
  homeIssueTime: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 34,
    padding: 10,
    radius: 17,
    w: 104,
  },
  homeHero: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'start',
    direction: 'column',
    gap: 30,
    h: 560,
    padding: 84,
    w: 1180,
    widthMode: 'fill',
  },
  homeHeroCopy: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 18,
    h: 302,
    w: 780,
  },
  homeHeroTitle: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 204,
    w: 760,
  },
  homeHeroText: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 80,
    w: 650,
  },
  homeHeroActions: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    gap: 12,
    h: 46,
    w: 300,
  },
  homePrimaryAction: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 44,
    padding: 14,
    radius: 22,
    w: 136,
  },
  homeSecondaryAction: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 44,
    padding: 14,
    radius: 22,
    w: 146,
  },
  homeMeta: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'stretch',
    direction: 'row',
    h: 150,
    padding: 48,
    w: 1180,
    widthMode: 'fill',
  },
  homeByline: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 72,
    w: 352,
    widthMode: 'fill',
  },
  homeBylineLabel: TEXT_LEAF_STATE,
  homeBylineValue: {
    ...TEXT_LEAF_STATE,
    h: 26,
    w: 190,
  },
  homeBylineNote: TEXT_LEAF_STATE,
  homeCategory: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 72,
    w: 352,
    widthMode: 'fill',
  },
  homeCategoryLabel: TEXT_LEAF_STATE,
  homeCategoryValue: {
    ...TEXT_LEAF_STATE,
    h: 26,
    w: 190,
  },
  homeCategoryNote: TEXT_LEAF_STATE,
  homeReadTime: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 72,
    w: 352,
    widthMode: 'fill',
  },
  homeReadTimeLabel: TEXT_LEAF_STATE,
  homeReadTimeValue: {
    ...TEXT_LEAF_STATE,
    h: 26,
    w: 190,
  },
  homeReadTimeNote: TEXT_LEAF_STATE,
  homeArticle: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'stretch',
    direction: 'row',
    gap: 52,
    h: 430,
    padding: 72,
    w: 1180,
    widthMode: 'fill',
  },
  homeEssay: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 26,
    h: 286,
    w: 690,
    widthMode: 'fill',
  },
  homeEssayHeading: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 42,
    w: 620,
    widthMode: 'fill',
  },
  homeChapterList: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    h: 218,
    w: 690,
    widthMode: 'fill',
  },
  homeChapterOne: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    h: 68,
    w: 690,
    widthMode: 'fill',
  },
  homeChapterOneTitle: { ...TEXT_LEAF_STATE, w: 520 },
  homeChapterOneNumber: TEXT_LEAF_STATE,
  homeChapterTwo: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    h: 68,
    w: 690,
    widthMode: 'fill',
  },
  homeChapterTwoTitle: { ...TEXT_LEAF_STATE, w: 520 },
  homeChapterTwoNumber: TEXT_LEAF_STATE,
  homeChapterThree: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    h: 68,
    w: 690,
    widthMode: 'fill',
  },
  homeChapterThreeTitle: { ...TEXT_LEAF_STATE, w: 520 },
  homeChapterThreeNumber: TEXT_LEAF_STATE,
  homeQuote: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 28,
    h: 286,
    w: 330,
  },
  homeQuoteHeading: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 42,
    w: 330,
    widthMode: 'fill',
  },
  homeQuoteList: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    h: 218,
    w: 330,
    widthMode: 'fill',
  },
  homeQuoteOne: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    h: 68,
    w: 330,
    widthMode: 'fill',
  },
  homeQuoteOneText: { ...TEXT_LEAF_STATE, widthMode: 'fill' },
  homeQuoteTwo: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    h: 68,
    w: 330,
    widthMode: 'fill',
  },
  homeQuoteTwoText: { ...TEXT_LEAF_STATE, widthMode: 'fill' },
  homeQuoteThree: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    h: 68,
    w: 330,
    widthMode: 'fill',
  },
  homeQuoteThreeText: { ...TEXT_LEAF_STATE, widthMode: 'fill' },
  homeDispatches: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 28,
    h: 392,
    padding: 72,
    w: 1180,
    widthMode: 'fill',
  },
  homeDispatchHeading: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 44,
    w: 520,
  },
  homeDispatchGrid: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'row',
    gap: 24,
    h: 176,
    w: 1036,
    widthMode: 'fill',
  },
  homeDispatchOne: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 14,
    h: 176,
    padding: 24,
    radius: 22,
    w: 329,
    widthMode: 'fill',
  },
  homeDispatchOneTitle: {
    ...TEXT_LEAF_STATE,
    h: 30,
    w: 260,
    widthMode: 'fill',
  },
  homeDispatchOneText: {
    ...TEXT_LEAF_STATE,
    h: 72,
    w: 260,
    widthMode: 'fill',
  },
  homeDispatchTwo: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 14,
    h: 176,
    padding: 24,
    radius: 22,
    w: 329,
    widthMode: 'fill',
  },
  homeDispatchTwoTitle: {
    ...TEXT_LEAF_STATE,
    h: 30,
    w: 260,
    widthMode: 'fill',
  },
  homeDispatchTwoText: {
    ...TEXT_LEAF_STATE,
    h: 72,
    w: 260,
    widthMode: 'fill',
  },
  homeDispatchThree: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    direction: 'column',
    gap: 14,
    h: 176,
    padding: 24,
    radius: 22,
    w: 330,
    widthMode: 'fill',
  },
  homeDispatchThreeTitle: {
    ...TEXT_LEAF_STATE,
    h: 30,
    w: 260,
    widthMode: 'fill',
  },
  homeDispatchThreeText: {
    ...TEXT_LEAF_STATE,
    h: 72,
    w: 260,
    widthMode: 'fill',
  },
  homeNewsletter: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'column',
    gap: 18,
    h: 264,
    padding: 72,
    w: 1180,
    widthMode: 'fill',
  },
  homeNewsletterHeading: {
    ...TEXT_LEAF_STATE,
    h: 44,
    w: 560,
  },
  homeNewsletterText: {
    ...TEXT_LEAF_STATE,
    h: 52,
    w: 620,
  },
  homeNewsletterAction: {
    ...EMPTY_STATE,
    ...HUG_BOX_LAYOUT,
    h: 42,
    padding: 14,
    radius: 21,
    w: 148,
  },
  homeFooter: {
    ...EMPTY_STATE,
    ...HUG_AUTO_LAYOUT_FRAME,
    align: 'center',
    direction: 'row',
    distribution: 'space-between',
    h: 92,
    padding: 42,
    w: 1180,
    widthMode: 'fill',
  },
  homeFooterBrand: { ...TEXT_LEAF_STATE, w: 180 },
  homeFooterNote: { ...TEXT_LEAF_STATE, w: 420 },
} satisfies Record<FigmaHomeDesignNodeId, FigmaDesignNodeState>)

export const FIGMA_HOME_DESIGN_DOCUMENT_NODES = createHomeNodes()

function createHomeNodes(): readonly DesignNode[] {
  return HOME_NODE_SEEDS.map(([id, parentId, intrinsic, label]) => {
    const state = HOME_NODE_STATES[id]
    const component = getHomeComponentBinding(id)
    const props: DesignJSONObject = {
      ...(HOME_CLASS_NAMES[id] ? { className: HOME_CLASS_NAMES[id] } : {}),
      ...(id === 'homeHero' ? { position: 'relative' } : {}),
      ...(intrinsic === 'button' ? { type: 'button' } : {}),
    }

    return {
      id,
      label,
      definition: component?.slotId === 'root'
        ? { kind: 'component', id: component.definitionId }
        : { kind: 'intrinsic', id: intrinsic },
      children: HOME_NODE_SEEDS
        .filter(([, candidateParentId]) => candidateParentId === id)
        .map(([childId]) => childId),
      props,
      text: HOME_TEXT[id as keyof typeof HOME_TEXT] ?? null,
      layout: createFigmaDesignNodeLayout(state),
      style: createFigmaDesignNodeStyle(state),
      frame: parentId === null
        ? {
            x: 1528,
            y: 76,
            width: 1280,
            height: 800,
            rotation: 0,
            widthMode: 'fixed',
            heightMode: 'content',
            overflow: 'scroll',
          }
        : null,
      component,
    }
  })
}

function getHomeComponentBinding(
  nodeId: FigmaHomeDesignNodeId,
): DesignNodeComponentBinding | null {
  for (const definition of FIGMA_HOME_COMPONENT_METADATA) {
    for (const instance of definition.instances) {
      for (const [slotId, slotNodeId] of Object.entries(instance.slots)) {
        if (slotNodeId === nodeId) {
          return {
            definitionId: definition.id,
            instanceId: instance.id,
            slotId,
          }
        }
      }
    }
  }

  return null
}

function mapHomeNodeStates(
  states: Record<FigmaHomeDesignNodeId, FigmaDesignNodeState>,
): Record<FigmaHomeDesignNodeId, FigmaDesignNodeState> {
  return Object.fromEntries(
    Object.entries(states).map(([nodeId, state]) => [
      nodeId,
      normalizeFigmaDesignNodeState(state),
    ]),
  ) as Record<FigmaHomeDesignNodeId, FigmaDesignNodeState>
}
