import type { CanvasBuiltinTool } from '../../core'

export const CANVAS_AFFORDANCE_CONFIG_GROUPS = [
  'commands',
  'gestures',
  'overlays',
  'shortcuts',
  'tools',
] as const

export type CanvasAffordanceConfigGroup =
  (typeof CANVAS_AFFORDANCE_CONFIG_GROUPS)[number]

type CanvasAffordanceConfigCatalog = Readonly<{
  commands: Readonly<Record<string, boolean>>
  gestures: Readonly<Record<string, boolean>>
  overlays: Readonly<Record<string, boolean>>
  shortcuts: Readonly<Record<string, boolean>>
  tools: Readonly<Record<CanvasBuiltinTool, boolean>>
}>

export const CANVAS_AFFORDANCE_CONFIG_DEFAULTS = Object.freeze({
  commands: Object.freeze({
    alignBottom: true,
    alignCenter: true,
    alignLeft: true,
    alignMiddle: true,
    alignRight: true,
    alignTop: true,
    copy: true,
    bringForward: true,
    bringToFront: true,
    cut: true,
    delete: true,
    duplicate: true,
    distributeHorizontal: true,
    distributeVertical: true,
    fitView: true,
    group: true,
    lockSelection: true,
    nudge: true,
    paste: true,
    redo: true,
    selectAll: true,
    sendBackward: true,
    sendToBack: true,
    undo: true,
    ungroup: true,
    unlockAll: true,
    zoomIn: true,
    zoomOut: true,
    zoomReset: true,
  }),
  gestures: Object.freeze({
    altDragDuplicate: true,
    createArrow: true,
    createComment: true,
    createCustom: true,
    createSection: true,
    createSticky: true,
    drawHighlight: true,
    drawMarker: true,
    eraseDrawing: true,
    laserPointer: true,
    createRect: true,
    createText: true,
    marquee: true,
    move: true,
    pan: true,
    resize: true,
    snapToAlignment: true,
    snapToGrid: true,
    snapToSpacing: true,
    temporaryPan: true,
    textEdit: true,
    wheelZoom: true,
  }),
  overlays: Object.freeze({
    alignmentGuides: true,
    componentPalette: true,
    draftArrow: true,
    draftRect: true,
    draftStroke: true,
    cursorChat: true,
    drawingControls: true,
    findReplace: true,
    grid: true,
    imageControls: true,
    inspector: true,
    itemOutline: true,
    laserTrail: true,
    marquee: true,
    presence: true,
    resizeHandles: true,
    selectionBounds: true,
    sessionTimer: true,
    spotlight: true,
    spacingGuides: true,
    stampControls: true,
    stickyQuickCreate: true,
    status: true,
    textEditor: true,
    toolbar: true,
    votingSession: true,
    zoomControls: true,
  }),
  shortcuts: Object.freeze({
    arrowTool: true,
    commentTool: true,
    copy: true,
    bringForward: true,
    bringToFront: true,
    cursorChat: true,
    cut: true,
    delete: true,
    duplicate: true,
    escape: true,
    fitAll: true,
    fitSelection: true,
    findReplace: true,
    group: true,
    highlighterTool: true,
    eraserTool: true,
    laserTool: true,
    lockSelection: true,
    markerTool: true,
    nudge: true,
    panTool: true,
    paste: true,
    quickCreateSticky: true,
    rectTool: true,
    redo: true,
    sectionTool: true,
    selectAll: true,
    selectTool: true,
    sendBackward: true,
    sendToBack: true,
    stickyTool: true,
    temporaryPan: true,
    textTool: true,
    undo: true,
    ungroup: true,
    unlockAll: true,
    zoomIn: true,
    zoomOut: true,
    zoomReset: true,
  }),
  tools: Object.freeze({
    arrow: true,
    comment: true,
    highlight: true,
    marker: true,
    eraser: true,
    laser: true,
    pan: true,
    rect: true,
    section: true,
    select: true,
    sticky: true,
    text: true,
  }),
} satisfies CanvasAffordanceConfigCatalog)
