import type { CanvasComponentTemplate } from './CanvasComponentLibrary'

export const DEFAULT_CANVAS_COMPONENT_TEMPLATES = [
  {
    id: 'sticky',
    label: 'N',
    title: 'Sticky',
    body: 'Decision note',
    w: 188,
    h: 148,
    fill: '#fef3c7',
    stroke: '#eab308',
    accent: '#ca8a04',
    presentation: 'note-card',
  },
  {
    id: 'label',
    label: 'T',
    title: 'Label',
    body: 'Section label',
    w: 192,
    h: 52,
    fill: 'transparent',
    stroke: 'transparent',
    accent: '#111827',
    presentation: 'inline-label',
  },
  {
    id: 'card',
    label: 'C',
    title: 'Card',
    body: 'Concept block',
    w: 220,
    h: 128,
    fill: '#ffffff',
    stroke: '#cbd5e1',
    accent: '#2563eb',
    presentation: 'accent-card',
  },
  {
    id: 'connector',
    label: 'A',
    title: 'Connector',
    w: 220,
    h: 64,
    fill: 'transparent',
    stroke: '#475569',
    accent: '#475569',
    presentation: 'line-connector',
  },
  {
    id: 'section',
    label: 'F',
    title: 'Section',
    body: 'Workspace',
    w: 340,
    h: 220,
    fill: 'rgba(241, 245, 249, 0.42)',
    stroke: '#94a3b8',
    accent: '#64748b',
    presentation: 'section-frame',
  },
  {
    id: 'checklist',
    label: '✓',
    title: 'Checklist',
    items: ['Scope', 'Owner', 'Next'],
    w: 224,
    h: 156,
    fill: '#ffffff',
    stroke: '#cbd5e1',
    accent: '#16a34a',
    presentation: 'checklist-list',
  },
  {
    id: 'kanban',
    label: 'K',
    title: 'Queue',
    items: ['Now', 'Next', 'Later'],
    w: 214,
    h: 190,
    fill: '#f8fafc',
    stroke: '#cbd5e1',
    accent: '#7c3aed',
    presentation: 'kanban-stack',
  },
  {
    id: 'table',
    label: '#',
    title: 'Matrix',
    columns: ['A', 'B', 'C'],
    items: ['Impact', 'High', 'Med', 'Effort', 'Low', 'Med'],
    w: 260,
    h: 156,
    fill: '#ffffff',
    stroke: '#cbd5e1',
    accent: '#0891b2',
    presentation: 'matrix-table',
  },
  {
    id: 'vote',
    label: '•',
    title: 'Vote',
    body: '+1',
    w: 84,
    h: 84,
    fill: '#fee2e2',
    stroke: '#f87171',
    accent: '#dc2626',
    presentation: 'vote-badge',
  },
  {
    id: 'image',
    label: '▧',
    title: 'Image',
    body: 'Screenshot',
    w: 240,
    h: 154,
    fill: '#f8fafc',
    stroke: '#94a3b8',
    accent: '#0f766e',
    presentation: 'image-frame',
  },
] satisfies readonly CanvasComponentTemplate[]
