import type { CanvasItem } from '../canvas'

export const PRODUCT_CANVAS_INITIAL_SELECTION: string[] = []

export const PRODUCT_CANVAS_SEED_ITEMS: CanvasItem[] = [
  {
    h: 64,
    id: 'product-board-title',
    text: 'Launch workshop',
    type: 'text',
    w: 260,
    x: 88,
    y: 56,
  },
  {
    accent: '#0f766e',
    body: 'Capture signals from the first customer calls.',
    component: 'section',
    fill: '#ecfdf5',
    h: 360,
    id: 'product-section-signals',
    stroke: '#5eead4',
    title: 'Signals',
    type: 'component',
    w: 332,
    x: 88,
    y: 120,
  },
  {
    accent: '#7c3aed',
    body: 'Turn raw notes into concrete experiments.',
    component: 'section',
    fill: '#f5f3ff',
    h: 360,
    id: 'product-section-experiments',
    stroke: '#c4b5fd',
    title: 'Experiments',
    type: 'component',
    w: 332,
    x: 452,
    y: 120,
  },
  {
    accent: '#ea580c',
    body: 'Decide what ships this week.',
    component: 'section',
    fill: '#fff7ed',
    h: 360,
    id: 'product-section-decisions',
    stroke: '#fdba74',
    title: 'Decisions',
    type: 'component',
    w: 332,
    x: 816,
    y: 120,
  },
  {
    accent: '#0f766e',
    body: 'New users ask for examples before they start.',
    component: 'sticky',
    fill: '#ccfbf1',
    h: 132,
    id: 'product-sticky-examples',
    stroke: '#5eead4',
    title: '',
    type: 'component',
    w: 168,
    x: 120,
    y: 178,
  },
  {
    accent: '#ca8a04',
    body: 'Setup feels risky without a quick undo path.',
    component: 'sticky',
    fill: '#fef3c7',
    h: 132,
    id: 'product-sticky-undo',
    stroke: '#fde047',
    title: '',
    type: 'component',
    w: 168,
    x: 300,
    y: 178,
  },
  {
    accent: '#2563eb',
    body: 'Teams want a shared board they can reopen.',
    component: 'sticky',
    fill: '#dbeafe',
    h: 132,
    id: 'product-sticky-reopen',
    stroke: '#93c5fd',
    title: '',
    type: 'component',
    w: 168,
    x: 160,
    y: 332,
  },
  {
    accent: '#7c3aed',
    body: 'Add a starter board with real prompts.',
    component: 'sticky',
    fill: '#ede9fe',
    h: 132,
    id: 'product-sticky-starter',
    stroke: '#c4b5fd',
    title: '',
    type: 'component',
    w: 168,
    x: 484,
    y: 178,
  },
  {
    accent: '#be123c',
    body: 'Keep editing instant: select, type, Esc.',
    component: 'sticky',
    fill: '#ffe4e6',
    h: 132,
    id: 'product-sticky-editing',
    stroke: '#fda4af',
    title: '',
    type: 'component',
    w: 168,
    x: 636,
    y: 178,
  },
  {
    accent: '#4d7c0f',
    body: 'Smoke test reload after every workshop flow.',
    component: 'sticky',
    fill: '#ecfccb',
    h: 132,
    id: 'product-sticky-reload',
    stroke: '#bef264',
    title: '',
    type: 'component',
    w: 168,
    x: 524,
    y: 332,
  },
  {
    fill: '#ffffff',
    h: 96,
    id: 'product-decision-shape',
    shapeType: 'rect',
    stroke: '#111827',
    text: 'Ship starter board',
    type: 'shape',
    w: 184,
    x: 868,
    y: 206,
  },
  {
    h: 64,
    id: 'product-text',
    text: 'Review in Friday critique',
    type: 'text',
    w: 220,
    x: 852,
    y: 348,
  },
  {
    end: { x: 484, y: 244 },
    endAttachedTo: 'product-sticky-starter',
    h: 34,
    id: 'product-arrow-examples',
    routing: 'straight',
    start: { x: 288, y: 244 },
    startAttachedTo: 'product-sticky-examples',
    stroke: '#334155',
    strokeWidth: 2.5,
    text: 'turn into',
    type: 'arrow',
    w: 196,
    x: 288,
    y: 227,
  },
  {
    end: { x: 868, y: 254 },
    endAttachedTo: 'product-decision-shape',
    h: 28,
    id: 'product-arrow-decision',
    routing: 'elbow',
    start: { x: 692, y: 310 },
    startAttachedTo: 'product-sticky-editing',
    stroke: '#334155',
    strokeWidth: 2.5,
    text: '',
    type: 'arrow',
    w: 176,
    x: 692,
    y: 254,
  },
  {
    h: 150,
    id: 'product-marker-loop',
    opacity: 1,
    points: [
      { x: 840, y: 184 },
      { x: 1072, y: 176 },
      { x: 1098, y: 318 },
      { x: 824, y: 326 },
      { x: 840, y: 184 },
    ],
    stroke: '#475569',
    strokeWidth: 5,
    type: 'marker',
    w: 274,
    x: 824,
    y: 176,
  },
  {
    h: 42,
    id: 'product-highlight-reload',
    opacity: 0.38,
    points: [
      { x: 520, y: 402 },
      { x: 668, y: 392 },
      { x: 712, y: 410 },
    ],
    stroke: '#fde047',
    strokeWidth: 18,
    type: 'highlight',
    w: 192,
    x: 520,
    y: 389,
  },
  {
    h: 32,
    id: 'product-comment-1',
    body: 'Needs a short example set.',
    thread: [
      {
        authorName: 'PM',
        body: 'Needs a short example set.',
        createdAt: '2026-06-03T10:00:00.000Z',
        id: 'product-comment-1:message-1',
      },
    ],
    type: 'comment',
    w: 32,
    x: 1100,
    y: 284,
  },
  {
    h: 32,
    id: 'product-stamp-yes',
    label: '+1',
    stamp: 'thumbs-up',
    type: 'stamp',
    w: 32,
    x: 1056,
    y: 194,
  },
  {
    h: 32,
    id: 'product-stamp-question',
    label: '?',
    stamp: 'question',
    type: 'stamp',
    w: 32,
    x: 1094,
    y: 194,
  },
]
